name: pass_flutter
version: 2.0.1
description: A Flutter library for getting and reading Apple Wallet passes.
homepage: https://github.com/alexeynobody/pass-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.2
  dio: ^5.1.1
  path_provider: ^2.0.2
  uuid: ^3.0.4
  path: ^1.8.0
  equatable: ^2.0.2
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
